# Generated by Django 5.0.4 on 2024-05-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='Tiltle',
            new_name='Title',
        ),
    ]
